src/objects/Int_Agreement__c.object
<CustomObject>
    <description>Int Agreement</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Agreement</label>
    <nameField>
        <displayFormat>AGR-{0000000000}</displayFormat>
        <label>Agreement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_Agreement_Classification__c.object
<CustomObject>
    <description>Int Agreement Classification</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Agreement Classification</label>
    <nameField>
        <displayFormat>ACI-{0000000000}</displayFormat>
        <label>Agreement Classification Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Classification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_Agreement_Exposure__c.object
<CustomObject>
    <description>Int Agreement Exposure</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Agreement Exposure</label>
    <nameField>
        <displayFormat>AGE-{0000000000}</displayFormat>
        <label>Agreement Exposure Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Exposure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_Agreement_Line_Feature__c.object
<CustomObject>
    <description>Int Agreement Line Feature</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed check box</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Agreement Line Feature</label>
    <nameField>
        <displayFormat>AFI-{0000000000}</displayFormat>
        <label>Agreement Feature Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreement Line Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_Agreement_Party__c.object
<CustomObject>
    <description>Int Agreement Party</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed check box</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Agreement Party</label>
    <nameField>
        <displayFormat>API-{0000000000}</displayFormat>
        <label>Agreement Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_Agreement_Payment_Schedule__c.object
<CustomObject>
    <description>Int Agreement Payment Schedule</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed check box</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Agreement Payment Schedule</label>
    <nameField>
        <displayFormat>APS-{0000000000}</displayFormat>
        <label>Agreement Payment Schedule Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Agreements Payment Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_Asset__c.object
<CustomObject>
    <description>Int Asset</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed check box</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Asset</label>
    <nameField>
        <displayFormat>AST-{0000000000}</displayFormat>
        <label>Asset Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_Delivery_Control__c.object
<CustomObject>
    <description>Int Delivery Control</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed check box</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Delivery Control</label>
    <nameField>
        <displayFormat>DEL-{0000000000}</displayFormat>
        <label>Delivery Control Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Delivery Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_File_Control__c.object
<CustomObject>
    <description>Int File Control</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed check box</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int File Control</label>
    <nameField>
        <displayFormat>FCI-{0000000000}</displayFormat>
        <label>File Control Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Files Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_Party__c.object
<CustomObject>
    <description>Int Party</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed check box</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Party</label>
    <nameField>
        <displayFormat>PAR-{0000000000}</displayFormat>
        <label>Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_Party_External_Reference__c.object
<CustomObject>
    <description>Int Party External Reference</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed check box</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Party External Reference</label>
    <nameField>
        <displayFormat>PER-{0000000000}</displayFormat>
        <label>Party External Reference Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Party External References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_Party_Feature__c.object
<CustomObject>
    <description>Int Party Feature</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed check box</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Party Feature</label>
    <nameField>
        <displayFormat>PFI-{0000000000}</displayFormat>
        <label>Party Feature Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Party Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Int_Party_Street_Address__c.object
<CustomObject>
    <description>Int Party Street Address</description>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Committed check box</description>
        <label>Committed</label>
        <type>Checkbox</type>
    </fields>
    <label>Int Party Street Address</label>
    <nameField>
        <displayFormat>PSA-{0000000000}</displayFormat>
        <label>Party Street Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int Party Street Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DMBIDataCleanupJob_Test.cls
@isTest public class DMBIDataCleanupJob_Test {
    public static testmethod void validateCleanUpJob(){
        int_agreement__c agr = DMBIInterfaceJobDataFactory.createagreement();
        agr.Committed__c = true;
        update agr;
        int_file_control__c fc = DMBIInterfaceJobDataFactory.createFilecontrol();
        Int_Asset__c asset = DMBIInterfaceJobDataFactory.createAsset();
        int_party__c party = DMBIInterfaceJobDataFactory.createEParty();
        int_delivery_control__c dc = DMBIInterfaceJobDataFactory.createDeliverycontrol();
        int_party_feature__c pf = DMBIInterfaceJobDataFactory.createPartyFeature(agr); 
        Int_Agreement_line_Feature__c ial = DMBIInterfaceJobDataFactory.createAgrlinefeature(agr);
        Int_Agreement_Party__c iap = DMBIInterfaceJobDataFactory.createAgrParty(agr);
        Int_Agreement_Exposure__c ae = DMBIInterfaceJobDataFactory.createAgrExposure(agr);
        Int_Agreement_Classification__c ac =DMBIInterfaceJobDataFactory.createAgrClassification(agr);
        /*Int_Party_External_Reference__c per = DMBIInterfaceJobDataFactory.createExernalRef(agr);
         Int_Party_Street_Address__c psa = DMBIInterfaceJobDataFactory.createStreetAddress(agr);
Int_Agreement_Payment_Schedule__c aps = DMBIInterfaceJobDataFactory.createpaymentShedule(agr);
        */
        List<String> ObjectSet = new List<string>{'Int_Agreement_Classification__c','Int_Agreement_Exposure__c','Int_Agreement_Party__c','Int_Agreement_line_Feature__c','int_party_feature__c','int_party__c','Int_Asset__c','Int_file_control__c','Int_Delivery_control__c','Int_Agreement__c'};
            for(string ObjectName : ObjectSet){
                Database.executeBatch(new DMBIDataCleanUpJob(ObjectName),1000);
        
             }
     }
}